name: hello-world
on: push
jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Say Hello World!
      run: echo "$(cat hello_world.txt)"
    - name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: install node dependencies
      run: npm install
    - name: build project
      run: npm run build
