name: build-test-deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: use node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: install node dependencies
      run: npm install
    - name: build the project
      run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install node dependencies
        run: npm install
      - name: run project tests
        run: npm test
        
